# Generated by Django 5.1.7 on 2025-03-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compound',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.CharField(blank=True, max_length=100, null=True)),
                ('mat1', models.CharField(blank=True, max_length=30, null=True)),
                ('mat1_fraction', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('mat2', models.CharField(blank=True, max_length=30, null=True)),
                ('mat2_fraction', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('mat3', models.CharField(blank=True, max_length=30, null=True)),
                ('mat3_fraction', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('co2kg_compound', models.DecimalField(blank=True, decimal_places=19, max_digits=19, null=True)),
                ('market', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='material_name')),
                ('kg_eq', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='kg_eq')),
                ('cost', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='cost')),
            ],
        ),
    ]
