# Generated by Django 5.1.7 on 2025-03-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='article',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='co2kg_compound',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='mat1',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='mat1_fraction',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='mat2',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='mat2_fraction',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='mat3',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='mat3_fraction',
        ),
        migrations.AddField(
            model_name='compound',
            name='Fuel_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='Fuel_type_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='Zero_carbon_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='green_premium_fuels',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='zero_carbon_option',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
