# Generated by Django 5.1.7 on 2025-03-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_remove_compound_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='material',
            name='kg_eq',
        ),
    ]
