# Generated by Django 5.1.7 on 2025-03-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_remove_material_cost_remove_material_kg_eq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='green_premium_fuels',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
